// Code generated by "stringer -type LogLevel"; DO NOT EDIT.

package log

import "strconv"

const _LogLevel_name = "NONEDEBUGWARN"

var _LogLevel_index = [...]uint8{0, 4, 9, 13}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
