// Code generated by "stringer -type LogLevel"; DO NOT EDIT.

package trace

import "strconv"

const _LogLevel_name = "LOG_NONELOG_DEBUGLOG_WARN"

var _LogLevel_index = [...]uint8{0, 8, 17, 25}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
