#+STARTUP: showeverything
#+STARTUP: indent
# Local Variables:
# fill-column: 120
# End:
# C-c a t 2 r - show all DONE items 
# Ctrl-Shift-Return - add new
# C-c / t - show todos only
* TODO Research "bleve zip" and "bleve scorch" commands
  - Note taken on [2018-10-14 Sun 11:51] \\
    Though I'm not sure if I totally care. I have many things to read and I don't see the purpose of fully understanding
    this if I don't have further troubles with scorch.
  - Note taken on [2018-10-09 Tue 10:22] \\
    as suggested by @mschoch on gitter.im
* TODO Design: How to batch index documents?
  index         // The index to create a batch and process it
  batch         // The currently active batch
                // - Attempts to send to the batcher should drop items on the floor after finish.
                // - Receivers should stop reading from arrivals. Any theortical messages-in-fligt will be dropped.

  size          // The size of a batch
** Atlas Design
index         // The bleve.Index

// --- Reader --- //
N/A

// --- Writer --- //
// consider filling up a channel with items, when it is full, send the channel's contents downstream for batch processing.
* TODO Have a plan for describing, indexing, and recalling words with multiple meanings
  - Note taken on [2018-10-14 Sun 07:42] \\
    As an example, the word 'terminal' has different meanings based on its context.
    If the context is "shell scripting", then terminal means that thing you're
    typing into. 
    
    If the context is "Backus–Naur Form" then 'terminal' means "tokens",
    "smallest block in our BNF grammar".

    It is clear in this case, we don't want to treat terms and defintions simply as
    terminal (title) => thing you're typing into (body)
    We'll need some other attribute to describe the idea of context; Or perhaps deduce
    context from the body.
  
