#+STARTUP: showeverything
#+STARTUP: indent
# Local Variables:
# fill-column: 120
# End:
# C-c a t 2 r - show all DONE items 
# Ctrl-Shift-Return - add new
# C-c / t - show todos only
* DONE Research "bleve zip" and "bleve scorch" commands
  - Note taken on [2018-10-14 Sun 11:51] \\
    Though I'm not sure if I totally care. I have many things to read and I don't see the purpose of fully understanding
    this if I don't have further troubles with scorch.
* DONE Design: How to batch index documents?
After watching the talk 
Rethinking Classical Concurrency Patterns video from Bryan C. Mills
I've concluded that I would avoid an async API at the 'library' level. In other words, deferring dealing with blocking
to the UI.
* TODO Have a plan for describing, indexing, and recalling words with multiple meanings
  - Note taken on [2018-10-14 Sun 07:42] \\
    As an example, the word 'terminal' has different meanings based on its context.
    If the context is "shell scripting", then terminal means that thing you're
    typing into. 
    
    If the context is "Backus–Naur Form" then 'terminal' means "tokens",
    "smallest block in our BNF grammar".

    It is clear in this case, we don't want to treat terms and defintions simply as
    terminal (title) => thing you're typing into (body)
    We'll need some other attribute to describe the idea of context; Or perhaps deduce
    context from the body.
